<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsUraPlugin>true</IsUraPlugin>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2026.3.9</Version>

    <!-- URA 插件元数据 -->
    <PluginInternalName>SkillTipsResponseAnalyzer</PluginInternalName>
    <PluginDisplayName>育成结束时给出评分最大化的技能点法</PluginDisplayName>
    <PluginAuthor>离披&amp;Github Contributors</PluginAuthor>
    <PluginDescription>有时候会有1~10分的误差，数据更新不及时会不准，精度不高仅供参考</PluginDescription>
    <PluginRepositoryUrl>https://github.com/URA-Plugins/SkillTipsResponseAnalyzer</PluginRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="i18n\ParseSkillTipsResponse.Designer.cs">
      <DependentUpon>ParseSkillTipsResponse.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="i18n\ParseSkillTipsResponse.resx">
      <LastGenOutput>ParseSkillTipsResponse.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="UmamusumeResponseAnalyzer" Version="*" PrivateAssets="all" />
  </ItemGroup>

</Project>
