name: Plugin
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  plugin:
    permissions:
      contents: write
    uses: URA-Plugins/.github/.github/workflows/plugin.yml@v1
    with:
      project: SkillTipsResponseAnalyzer.csproj
      publish: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
